### ISSUE TITLE
Great Idea, Documentation needs Help

### ISSUE THREAD

**Issue by FiberJW** [RyanBluth/Mangy-Bat#1]
Hey!

I find this tool idea really cool, but I don't know how to use it. Could you provide installation instructions, system requirements, and a download in the readme?

Thanks

**Comment by RyanBluth** [comment]
Sure, which part are you confused about? You'll need download the release which can be found here -

https://github.com/RyanBluth/Mangy-Bat/releases/tag/2.1

Once extracted  you will need to copy all of the files from the dist folder to some location on your computer -  for example C:\tools\mangy

Add this location to your PATH like so - http://www.computerhope.com/issues/ch000549.htm

Once this is done you should be able to open a command prompt and run the command "mangy"

I will make an installation section with this information in the readme.
